// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "FakeNumber DNO",
            "url": "https://github.com/drewkosta/realNumberDNOClone"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/api-keys": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a new API key for an organization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Generate API key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "apiKey": {
                                    "type": "string"
                                },
                                "note": {
                                    "type": "string"
                                },
                                "orgId": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke an organization's API key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Revoke API key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/itg-ingest": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ingest a phone number from an ITG traceback investigation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Ingest ITG number",
                "parameters": [
                    {
                        "description": "ITG ingest details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.ITGIngestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.DNONumber"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/npac-event": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Process a mock NPAC number porting event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "NPAC porting event",
                "parameters": [
                    {
                        "description": "Porting event details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "newOwnerOrgId": {
                                    "type": "integer"
                                },
                                "newStatus": {
                                    "type": "string"
                                },
                                "phoneNumber": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/reset-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin resets another user's password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Reset user password",
                "parameters": [
                    {
                        "description": "User ID and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "newPassword": {
                                    "type": "string"
                                },
                                "userId": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/tss-sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Trigger a mock TSS registry synchronization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "TSS registry sync",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "numbersAdded": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new user account (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve DNO analytics summary",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get analytics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.AnalyticsSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analyzer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Analyze call traffic records against the DNO list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyzer"
                ],
                "summary": "Analyze traffic",
                "parameters": [
                    {
                        "description": "Traffic records to analyze",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.DNOAnalyzerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.DNOAnalyzerReport"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/audit-log": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a paginated audit log of DNO operations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get audit log",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.AuditLogPage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate with email and password, returns JWT access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Exchange a refresh token for a new access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refreshToken": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/compliance-report": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a compliance report for the current organization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compliance"
                ],
                "summary": "Generate compliance report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.ComplianceReport"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dno/bulk-job": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the status of a bulk upload job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bulk Operations"
                ],
                "summary": "Get bulk job status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bulk job ID",
                        "name": "jobId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.BulkJob"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dno/bulk-upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a CSV file of phone numbers for bulk addition to the DNO list",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bulk Operations"
                ],
                "summary": "Bulk upload DNO numbers",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file of phone numbers",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Channel (defaults to voice)",
                        "name": "channel",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Number type (defaults to local)",
                        "name": "numberType",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "jobId": {
                                    "type": "integer"
                                },
                                "message": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                },
                                "totalRecords": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dno/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Download all DNO numbers as a CSV file",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "Bulk Operations"
                ],
                "summary": "Export DNO numbers as CSV",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/dno/numbers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a paginated list of DNO numbers with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DNO Management"
                ],
                "summary": "List DNO numbers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by dataset",
                        "name": "dataset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by channel",
                        "name": "channel",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.DNONumberPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a phone number on the Do-Not-Originate list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DNO Management"
                ],
                "summary": "Add a DNO number",
                "parameters": [
                    {
                        "description": "Number to add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.AddDNORequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.DNONumber"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a phone number from the Do-Not-Originate list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DNO Management"
                ],
                "summary": "Remove a DNO number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phone number to remove",
                        "name": "phoneNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Channel (defaults to voice)",
                        "name": "channel",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dno/query": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": [],
                        "BearerAuth": []
                    }
                ],
                "description": "Check if a phone number is on the Do Not Originate list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Single DNO lookup",
                "parameters": [
                    {
                        "type": "string",
                        "example": "5551234567",
                        "description": "10-digit phone number",
                        "name": "phoneNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "voice",
                        "description": "voice or text",
                        "name": "channel",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.DNOQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dno/query/bulk": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": [],
                        "BearerAuth": []
                    }
                ],
                "description": "Check up to 1000 phone numbers against the DNO list in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Bulk DNO lookup",
                "parameters": [
                    {
                        "description": "Phone numbers and channel",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.BulkQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.BulkQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dno/validate-ownership": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Check whether the current organization owns a given phone number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DNO Management"
                ],
                "summary": "Validate number ownership",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phone number to validate",
                        "name": "phoneNumber",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.OwnershipValidation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roi-calculator": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Calculate return on investment based on daily call volume",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tools"
                ],
                "summary": "Calculate ROI",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Daily call volume",
                        "name": "dailyCallVolume",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.ROICalculation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/webhooks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all webhook subscriptions for the current organization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhooks"
                ],
                "summary": "List webhooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/realNumberDNOClone_internal_models.WebhookSubscription"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new webhook subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhooks"
                ],
                "summary": "Create webhook",
                "parameters": [
                    {
                        "description": "Webhook details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "events": {
                                    "type": "string"
                                },
                                "secret": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/realNumberDNOClone_internal_models.WebhookSubscription"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a webhook subscription",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhooks"
                ],
                "summary": "Delete webhook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Webhook ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "realNumberDNOClone_internal_models.AddDNORequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "numberType": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.AnalyticsSummary": {
            "type": "object",
            "properties": {
                "activeNumbers": {
                    "type": "integer"
                },
                "byChannel": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "byDataset": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "byNumberType": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "hitRate24h": {
                    "type": "number"
                },
                "queriesByHour": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/realNumberDNOClone_internal_models.HourlyCount"
                    }
                },
                "recentAdditions": {
                    "type": "integer"
                },
                "recentRemovals": {
                    "type": "integer"
                },
                "totalDnoNumbers": {
                    "type": "integer"
                },
                "totalQueries24h": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.AuditLog": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "entityId": {
                    "type": "integer"
                },
                "entityType": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "orgId": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.AuditLogPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/realNumberDNOClone_internal_models.AuditLog"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.BulkJob": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "errorCount": {
                    "type": "integer"
                },
                "fileName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jobType": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "processedRecords": {
                    "type": "integer"
                },
                "resultSummary": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "successCount": {
                    "type": "integer"
                },
                "totalRecords": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.BulkQueryRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "phoneNumbers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "realNumberDNOClone_internal_models.BulkQueryResponse": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "integer"
                },
                "misses": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/realNumberDNOClone_internal_models.DNOQueryResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.CDRRecord": {
            "type": "object",
            "properties": {
                "callerId": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.ComplianceReport": {
            "type": "object",
            "properties": {
                "channelCoverage": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "complianceStatus": {
                    "type": "string"
                },
                "datasetCoverage": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "enforcementMethod": {
                    "type": "string"
                },
                "generatedAt": {
                    "type": "string"
                },
                "last30DaysBlocked": {
                    "type": "integer"
                },
                "last30DaysHitRate": {
                    "type": "number"
                },
                "last30DaysQueries": {
                    "type": "integer"
                },
                "orgName": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "totalDnoNumbers": {
                    "type": "integer"
                },
                "updateFrequency": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.DNOAnalyzerReport": {
            "type": "object",
            "properties": {
                "byDataset": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "byThreatCategory": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "dnoHits": {
                    "type": "integer"
                },
                "dnoMisses": {
                    "type": "integer"
                },
                "estBlockedPerDay": {
                    "type": "integer"
                },
                "hitRate": {
                    "type": "number"
                },
                "topSpoofed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/realNumberDNOClone_internal_models.SpoofedNumber"
                    }
                },
                "totalRecords": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.DNOAnalyzerRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/realNumberDNOClone_internal_models.CDRRecord"
                    }
                }
            }
        },
        "realNumberDNOClone_internal_models.DNONumber": {
            "type": "object",
            "properties": {
                "addedByOrgId": {
                    "type": "integer"
                },
                "addedByUserId": {
                    "type": "integer"
                },
                "channel": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dataset": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "investigationId": {
                    "type": "string"
                },
                "numberType": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "threatCategory": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.DNONumberPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/realNumberDNOClone_internal_models.DNONumber"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.DNOQueryResponse": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "dataset": {
                    "type": "string"
                },
                "isDno": {
                    "type": "boolean"
                },
                "lastUpdated": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.HourlyCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "hour": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.ITGIngestRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "investigationId": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "threatCategory": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.LoginResponse": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/realNumberDNOClone_internal_models.User"
                }
            }
        },
        "realNumberDNOClone_internal_models.OwnershipValidation": {
            "type": "object",
            "properties": {
                "phoneNumber": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "realNumberDNOClone_internal_models.ROICalculation": {
            "type": "object",
            "properties": {
                "avgComplaintCost": {
                    "type": "number"
                },
                "complianceRiskLevel": {
                    "type": "string"
                },
                "dailyCallVolume": {
                    "type": "integer"
                },
                "estAnnualBlocked": {
                    "type": "integer"
                },
                "estAnnualSavings": {
                    "type": "number"
                },
                "estDailyBlocked": {
                    "type": "integer"
                },
                "estHitRate": {
                    "type": "number"
                },
                "estMonthlyBlocked": {
                    "type": "integer"
                }
            }
        },
        "realNumberDNOClone_internal_models.SpoofedNumber": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "dataset": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "threatCategory": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.User": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "realNumberDNOClone_internal_models.WebhookSubscription": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "events": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "orgId": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "description": "Organization API key for machine-to-machine access",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BearerAuth": {
            "description": "JWT Bearer token (prefix with \"Bearer \")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FakeNumber DNO API",
	Description:      "Do Not Originate database API for preventing illegal robocalls and caller ID spoofing.\nCarriers query the DNO database in real-time to block spoofed calls.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
